### ISSUE TITLE
How can Implement "server_recv()" function

### ISSUE THREAD

**Issue by Emprotek** [nneves/MBED-NXP-LPC1768-LWIP#1]
Hi,
I am using LPC1768 development board. I want use want to use Ethernet Port so I used MBED-NXP-LPC1768-LWIP which is attached here. But in this stack recv  is not working yet. So how can I implement this part. Because I want send some data into web server using post method and receive some data from web-server to micro controller board. So please can you help me how can I do that ??
If I uncommitted receive function then there is lot's of error occurred. If you completed receive function then can you share with me ??

Thanks & Regards,
Dinesh Thanth

# **static err_t server_recv(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err)
{ 
// NOTE: haven't finished porting c++ code to c, recv is not working yet!**

**Comment by nneves** [comment]
Hi Dinesh,

I haven't been much active on the hardware part, this project was a quick test I made back in 2012, not sure if the instructions are still correct. Sorry, I can't give you feedback, don't have the hardware setup, either time to check it. Also, there should be already some other projects in the community that do this better ;)

Good luck!
